### ISSUE TITLE
bin/ytblock won't execute in Ubuntu VM

### ISSUE THREAD

**Issue by shayaknyc** [foae/pihole-youtube-block#1]
Hey, running PiHole in an Ubuntu VM. Took a snapshot of the VM, installed golang-go and first tried running the primary command "go run main.go" and got this error:
```
# command-line-arguments
./main.go:147: undefined: strings.Builder

```
then went into bin and attempted to run "./ytblock" and got this error:
`-bash: ./ytblock: cannot execute binary file: Exec format error`

Obviously got the same error when running ./ytblock-rpi since the VM is not running an ARM architecture.....was the ytblock binary compiled for ARM anyway?

Also, I'm using: go version go1.6.2 linux/amd64

**Comment by foae** [comment]
You need to run go >= 1.10

If you run `go version` in your shell you should get your installed go version.

It's an easy fix, but unfortunately, as I later found out, using this program might prevent your device from playing legit clips, since all ads are served over the same domain with normal clips. Therefore, until I find a better solution, I'd personally recommend you not to use it – unless you like exploring and breaking things :-)

I'd recommend going over https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253/10

**Comment by shayaknyc** [comment]
Yeah, I just realized that my Ubuntu doesn't have go >=1.10 in the repo.....Thanks!
